---
kind: pipeline
name: cover_default

steps:
  - name: scan
    image: aosapps/drone-sonar-plugin
    environment:
      SONAR_TOKEN:
        from_secret: SONAR_TOKEN
  - name: build
    image: node
    commands:
      - cd cover
      - npm install
      - npm run build
---
kind: signature
hmac: ace3f926fd2a5aeb2b078d0ff05e6e8b3c8ad40e3fa3d48930b4a329d00b6fb4
