---
kind: pipeline
name: cover_default

steps:
  - name: scan
    image: committed/drone-sonarqube-node
    settings:
      level: DEBUG
      host: https://sonarcloud.io
      token:
        from_secret: SONAR_TOKEN
  - name: build
    image: node
    commands:
      - cd cover
      - npm install
      - npm run build
---
kind: signature
hmac: 4ff56fe360e7d175a85dc20453130104b67c0b1f3fe919c5209181fb2cbcb6dd

...
