---
kind: pipeline
name: cover_default

steps:
  - name: install_dependencies
    image: node
    commands:
      - cd cover
      - npm install
  - name: test
    image: node
    commands:
      - cd cover
      - npm run test
  - name: scan
    image: aosapps/drone-sonar-plugin
    commands:
      - cd cover
      - /bin/drone-sonar
    settings:
      usingProperties: true
      sonar_host: https://sonarcloud.io
      sonar_token:
        from_secret: SONAR_TOKEN
  - name: build
    image: node
    commands:
      - cd cover
      - npm run build
  - name: deploy_storybook
    image: chybie/node-aws-cli
    environment:
      AWS_ACCESS_KEY_ID:
        from_secret: AWS_ACCESS_TOKEN
      AWS_SECRET_ACCESS_KEY:
        from_secret: AWS_SECRET_KEY
    commands:
      - npm run deploy-storybook
---
kind: signature
hmac: 3a37ac40e4e1f5b07abc9dd155beadee7aab700f176d1916bd2d44965fbc8370
