---
kind: pipeline
name: cover_default

steps:
  - name: scan
    image: committed/drone-sonarqube-node
    settings:
      sonar_host: https://sonarcloud.io
      sonar_token:
        from_secret: SONAR_TOKEN
  - name: build
    image: node
    commands:
      - cd cover
      - npm install
      - npm run build
---
kind: signature
hmac: 47c6bebcf11f472cc2073b819306a37882697d66a34b66fd0b821e940309e461

...
