---
kind: pipeline
name: cover_default

steps:
  - name: install_dependencies
    image: node
    commands:
      - (cd cover && npm install); (cd librarian && npm install); (cd services/monocle && npm install); (cd services/mailroom && npm install)
  - name: scan
    image: aosapps/drone-sonar-plugin
    settings:
      usingProperties: true
      sonar_host: https://sonarcloud.io
      sonar_token:
        from_secret: SONAR_TOKEN
  - name: build
    image: node
    commands:
      - cd cover
      - npm run build
---
kind: signature
hmac: 79aaada727f07f79df35c9b9f75e6a4b6a3529c0a13e27933fe133380bee115d

...
