---
kind: pipeline
name: cover_default

steps:
  - name: scan
    image: committed/drone-sonarqube-node
    settings:
      usingProperties: true
      sonar_host: https://sonarcloud.io
      sonar_token:
        from_secret: SONAR_TOKEN
  - name: build
    image: node
    commands:
      - cd cover
      - npm install
      - npm run build
---
kind: signature
hmac: 2576d6bfd361b9b0393967637e806c8e48e0bbb0f912e1d7c751998a8be4d5ec

...
