---
kind: pipeline
name: cover_default

steps:
  - name: scan
    image: aosapps/drone-sonar-plugin
    settings:
      usingProperties: true
      sonar_host: https://sonarcloud.io
      sonar_token:
        from_secret: SONAR_TOKEN
  - name: build
    image: node
    commands:
      - cd cover
      - npm install
      - npm run build
---
kind: signature
hmac: 7fcecef713892132d0c2f51aa6eacdd409cda517f397cfc4912d3ec2b3bbce0b

...
