---
kind: pipeline
name: cover_default

steps:
  - name: scan
    image: aosapps/drone-sonar-plugin
    commands:
      - npm install -g typescript
    settings:
      usingProperties: true
      sonar_host: https://sonarcloud.io
      sonar_token:
        from_secret: SONAR_TOKEN
  - name: build
    image: node
    commands:
      - cd cover
      - npm install
      - npm run build
---
kind: signature
hmac: 955fa1b66c7fe6afe3073e453a701084884f8616f9c16853f7723b9e35151c59

...
