---
kind: pipeline
name: cover_default

steps:
  - name: install_dependencies
    image: node
    commands:
      - cd cover
      - npm install
  - name: test
    image: node
    commands:
      - cd cover
      - npm run test
  - name: scan
    image: aosapps/drone-sonar-plugin
    commands:
      - cd cover
      - /bin/drone-sonar
    settings:
      usingProperties: true
      sonar_host: https://sonarcloud.io
      sonar_token:
        from_secret: SONAR_TOKEN
  - name: build
    image: node
    commands:
      - cd cover
      - npm run build
  - name: deploy-staging
    image: amazon/aws-cli
    commands:
      - aws s3 sync ./build s3://pluteum-staging/ --delete
  - name: deploy_storybook
    image: chybie/node-aws-cli
    environment:
      AWS_ACCESS_KEY_ID:
        from_secret: AWS_ACCESS_TOKEN
      AWS_SECRET_ACCESS_KEY:
        from_secret: AWS_SECRET_KEY
    commands:
      - cd cover
      - npm run deploy-storybook
---
kind: signature
hmac: 5c89f39bee2d2ee29930b1a0cba58e67b272940e7e93e6302aa81ce1c9b1155a
