version: "3"
services:
  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - "./config/nginx.conf:/etc/nginx/nginx.conf:ro"
  cover:
    image: node:lts
    working_dir: /home/node/app
    command: /bin/sh -c "npm i && yarn start"
    ports:
      - "3000"
    volumes:
      - ./cover:/home/node/app
  librarian:
    image: node:12
    working_dir: /home/node/app
    ports:
      - "4000"
    command: /bin/sh -c "npm i && yarn start:docker"
    volumes:
      - ./librarian:/home/node/app
    env_file: .env
  monocle:
    image: node:lts
    working_dir: /home/node/app
    command: /bin/sh -c "yarn --silent && yarn start"
    volumes:
      - ./services/monocle:/home/node/app
    env_file: .env
  mailroom:
    image: node:lts
    working_dir: /home/node/app
    command: /bin/sh -c "yarn --silent && yarn start"
    volumes:
      - ./services/mailroom:/home/node/app
    env_file: .env
  postgres:
    image: postgres:12
    ports:
      - "5432"
    env_file: .env
    volumes:
      - "./storage/postgres:/var/lib/postgresql/data"
  minio:
    image: minio/minio
    command: "server /data"
    volumes:
      - "./storage/minio:/data"
    ports:
      - "9000:9000"
    env_file: .env
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "8080:15672"
